services:
  - type: web
    name: fast-youtube-converter
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true